drop type tipo_valor force;
drop type distribucion_exp force;
drop table VariedadVid cascade constraints;
drop table DenominacionDeOrigen cascade constraints;

drop type valoracion force;
drop type hechos_hist force;
drop type lugar force;
drop type conj_telefonos force;
drop type direccion force;
drop type personaDeContacto force;
drop type datosDeContacto force;
drop type premio force;
drop type escala force;
drop type costoInscripcion force;
drop type datosBancarios force;
drop type unidadMonetaria force;
drop type valoracion_nt force;
drop type publicaciones_nt force;
drop type hechos_hist_nt force;
drop type premio_nt force;
drop type escala_nt force;
drop type costoInscripcion_nt force;

drop table MuestraCompite cascade constraints purge;
drop table HistoricoPrecio cascade constraints purge;
drop table Presentacion cascade constraints purge;
drop table MarcaVino_B_DO cascade constraints purge;
drop table ClasificacionVinos cascade constraints purge;
drop table MarcaVino cascade constraints purge;
drop table MuestraCatador cascade constraints purge;
