drop table I_metricas_pais cascade constraints purge;
drop table I_metricas_concurso cascade constraints purge;
drop table I_tiempo cascade constraints purge;
drop table I_pais cascade constraints purge;
drop table I_continente cascade constraints purge;
drop table I_tipo_concurso cascade constraints purge;
drop sequence seq_Ipais;
drop sequence seq_Icontinente;
drop sequence seq_Itiempo;
drop sequence seq_Itipo_concurso;
drop sequence seq_Imetricas_pais;
drop sequence seq_Imetricas_concurso;

drop table I_tiempoAux cascade constraints purge;
drop table I_bodega cascade constraints purge;
drop table I_marca cascade constraints purge;
drop table I_critica cascade constraints purge;
drop table I_catador cascade constraints purge;
drop table I_paisAux cascade constraints purge;
drop table I_concurso cascade constraints purge;
